version: '3.9'

services:
  db:
    image: mysql:8.0.33
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: some-random-password-yay
      MYSQL_DATABASE: list_app_db
    ports:
      - '3306:3306'

  wait-db:
    image: toschneck/wait-for-it
    command: ['db:3306', '-t', '60']
    depends_on:
      - db

  api:
    build: './'
    ports:
      - '3000:3000'
    depends_on:
      wait-db:
        condition: service_completed_successfully
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: some-random-password-yay
      DB_NAME: list_app_db
